version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0
    branches:
      only:
        - master
        - feature/*
        - dependabot/*
    steps:
      - checkout
      - run: dotnet build -c release
      - run: dotnet test --no-build KnowYourLimits.UnitTests/KnowYourLimits.UnitTests.csproj
