version: 2
jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build
    branches:
      only:
        - master
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet test KnowYourLimits.UnitTests/KnowYourLimits.UnitTests.csproj
      - run: dotnet build -c release
      - run: nuget push -ApiKey NUGET_KEY KnowYourLimits.AspNetCore/bin/Release/KnowYourLimits.AspNetCore.1.0.0.nupkg
