name: .NET Core

on:
  push:
    branches-ignore: release/*

jobs:
  build:
    name: Build & Test
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Setup dotnet core 3.1.101 if needed
        uses: actions/setup-dotnet@v1.2.0
        with:
          dotnet-version:  3.1.101
        if: matrix.os == 'macOS-latest' || matrix.os == 'ubuntu-latest'
      - name: Build & Test
        run: |
          dotnet build --configuration Release
          dotnet test KnowYourLimits.UnitTests/KnowYourLimits.UnitTests.csproj
    
